version: '3.8'

services:
  smart_messenger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_messenger
    env_file:
      - .env
    ports:
      - '${API_PORT}:8000'
    command: 'uvicorn --factory api.main:create_app --host 0.0.0.0 --port 8000 --reload'
    depends_on:
      - smart_messenger_postgres
      - smart_messenger_mongodb
    volumes:
      - ./src:/app/src
    restart: unless-stopped

  smart_messenger_postgres:
    image: postgres:15
    container_name: smart_messenger_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - smart_messenger_pgdata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: unless-stopped

  smart_messenger_mongodb:
    image: mongo:8
    container_name: smart_messenger_mongodb
    env_file:
      - .env
    ports:
      - '${MONGODB_PORT}:27017'
    volumes:
      - smart_messenger_mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DB}
    restart: unless-stopped

volumes:
  smart_messenger_pgdata:
  smart_messenger_mongodata:
