[project]
name = "smartmessenger"
version = "0.1.0"
description = "ELEKS internship project"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic-settings>=2.9.1",
    "uvicorn>=0.34.2",
]
